image: node:16

licenses-custom:
  script:
    - cat ./npm-licenses.sh "(MIT OR GPL-3.0)" "Other License" | /bin/bash

  artifacts:
    when: always
    paths:
      - license_summary.txt
      - license_detailed.json
    expire_in: 3 days
    reports:
      junit: licenses.xml
