image: node:16

licenses-custom:
  script:
    #- ./npm-licenses.sh
    - sleep 1s

  artifacts:
    when: always
    paths:
      - license_summary.txt
      - license_detailed.json
    expire_in: 3 days
    reports:
      junit: test.xml
